"""fix typo magnitude

Revision ID: 369c55d8bf65
Revises: fe42ba0a71dc
Create Date: 2025-10-27 03:00:58.800351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369c55d8bf65'
down_revision = 'fe42ba0a71dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('magnitude', sa.Float(), nullable=True))
    op.drop_column('earthquakes', 'magnitud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('magnitud', sa.FLOAT(), nullable=True))
    op.drop_column('earthquakes', 'magnitude')
    # ### end Alembic commands ###
